### ISSUE TITLE
homematic-config: how do I configure node-red-contrib-homematic

### ISSUE THREAD

**Issue by FotoFieber** [firsttris/node-red-contrib-homematic#1]
The documentation lacks some hints for beginners:

-The homematic node shows "Add new homematic-config"
- How can I add it?

**Comment by firsttris** [comment]
Hello Foto Fieber,

if you select "Add new homematic-config" and click the edit symbol next to it you can create a new device. or you can select an existing device and edit it. no magic. (should be renamed to just "new") at the time i have done this, node-red had done it in their nodes the same way. node needs some updates.

i will create a newer easier one.

regards

**Comment by firsttris** [comment]
i rebuild the project, its now much easier.

best regards
Tristan
