### ISSUE TITLE
missing attributes in homematic.html

### ISSUE THREAD

**Issue by quito96** [firsttris/node-red-contrib-homematic#11]
Hi , i use  the latest Version 2.07.

when i try to set humidity attributes in the homematic node, i cant do that.
In the selection window the attribute is missing.
There are 30 attributes in the html file but in the node only 21.

How ca i fix this ??
BR Quito

![img_9726](https://user-images.githubusercontent.com/37045252/36947655-6b061bae-1fcf-11e8-954b-bac8ea23e8d4.JPG)
![img_6037](https://user-images.githubusercontent.com/37045252/36947656-6b1fbf78-1fcf-11e8-9548-cce6c13e3843.JPG)

**Comment by firsttris** [comment]
hey sir, have you restarted node-red after updating the node?

regards
Tristan

**Comment by quito96** [comment]
Hi tristan, 

Yes, i stop red node and restart the app. 
I removed the ver 2.06 and installed the latest version 2.07 , but it’s the same issue. 

Greetings from Guido

**Comment by firsttris** [comment]
when i find time i will test and report back

**Comment by quito96** [comment]
Hi Tristan,

my temporaly workflow…, but it works…

create the node with the correct Channel Name
set the Value to „state"
export the node to clipboard
oben new text file and import the clipboard
search and exchange „state“ with the value i need
export the text to clipboard and import in node red
:-) 
 
BR

**Comment by firsttris** [comment]
i just checked and after updating node-red-contrib-homematic i could see all attributes. so i guess there is some issue with your setup.

have you tried to remove the node-red-contrib-homematic verify its gone and install it again. 
maybe you have installed it on two different locations (globally and locally)? npm i vs. npm i -g

**Comment by quito96** [comment]
pi@quitos_rpi3:~ $ sudo npm i -g
+ json@1.0.0
added 1 package in 1.806s
pi@quitos_rpi3:~ $ sudo npm i   
npm WARN json@1.0.0 No description
npm WARN json@1.0.0 No repository field.

up to date in 0.914s
pi@quitos_rpi3:~ $ 

i think npm is only installed globally

**Comment by quito96** [comment]
the installation path: home/pi/.node-red/node_modules/node-red-contrib-homematic/

**Comment by firsttris** [comment]
since i can't reproduce your issue i can only suggest remove and re-install the plugin.

tested update and fresh install
![image](https://user-images.githubusercontent.com/1709260/37559400-d296cde4-2a25-11e8-8479-8d3165699060.png)
