### ISSUE TITLE
RAMP_TIME is missing

### ISSUE THREAD

**Issue by Poquaruse** [firsttris/node-red-contrib-homematic#12]
Hi there,

thank you very much for that great plugin! It works very nicely! :grinning: 
There's one small issue though: I'd like to change the RAMP_TIME of a dimmer channel. That attribute is missing unfortunately (the workaround of calling the URL with modified payload directly does work for now).

Could you please add it?

That brings up another point: wouldn't it be nice to have attributes as configurable nodes? If it were like this, it would be like adding/editing the homematic devices for example. There are a lot of data points / attributes and it wouldn't make sense to add them all, I guess. (Check out the document called "Homematic-Script Dokumentation - Teil 4: Datenpunkte - eQ-3"...)

Best regards!

**Comment by firsttris** [comment]
Hi Popuaruse and thank for ur message.

i added RAMP_TIME in 2.0.8

i think its a bigger advantage that people can eaily select ~ 30 commands and don't have to create them first. 

as i wrote in the readme you can very easily extend this module by just adding attributes to the html file. all pull-requests welcome.

regards
tristan

**Comment by Poquaruse** [comment]
Hi @firsttris,

wow, that was fast, thanks! :+1: 

I definitely know what you mean and you're probably right... I just feels a little bit hacky to change the "source code" (even if it is just the html...). On the other hand, it is true that being able to choose from the most important ones does help a lot. 

I'll come back here if I'm able to figure out a nice way to alleviate that.

Thanks again and have a nice weekend!
