### ISSUE TITLE
node.debug ist keine Funktion

### ISSUE THREAD

**Issue by resper** [firsttris/node-red-contrib-homematic#13]
Hallo,

ich nutze Node-Red in einer Docker Umgebung und als OS unRaid. Bei mir verursachen diese beiden Zeilen 

`        node.debug("Extracting custom payload!");
        node.debug(JSON.stringify(msg));`

in der homematic.js einen Fehler (node.debug ist keine Funktion). Nachdem ich sie bei mir raus genommen habe, funktioniert es einwandfrei.

**Comment by firsttris** [comment]
ok dann entferne ich dies, danke dir!
