### ISSUE TITLE
Support for HomeMatic Wireless Window Drive WinMatic?

### ISSUE THREAD

**Issue by misosec** [firsttris/node-red-contrib-homematic#15]
Hello,
does this addon support HomeMatic Wireless Window Drive WinMatic? 

Thank you.

**Comment by firsttris** [comment]
With HomeMatic Wireless you mean Homematic IP?

The question is does it have the same XML-RPC Api? If yes i does support it.

**Comment by misosec** [comment]
Hello,
it is not Homematic IP. I have connected it to my CCU2.

**Comment by misosec** [comment]
btw, here is the device:
https://www.eq-3.com/products/homematic/windows-and-doors/homematic-wireless-window-drive-winmatic.html

I have your addon connected to my CCU2, I have added device but I do not know what attribute and value to set for setValue function.

**Comment by misosec** [comment]
Hello again,
any idea how could I make it to work?
thanks

**Comment by firsttris** [comment]
Hey Sir
I think you just need to find out which command to send to your device.

Should be similar to any other Homematic device.

From
https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitWinMaticService.js

I would say the are doing set LEVEL, DIRECTION and SPEED.

You should be able to query those values and find out.

Best regards
Tristan

**Comment by firsttris** [comment]
You can extend homematic.html of this node if something is missing

**Comment by misosec** [comment]
Thank you. i will look into it.
Just to be sure... What should be the channel in device settings node? See attached image, please.
Thank you again.
![image-001 22-06-14](https://user-images.githubusercontent.com/29805226/40891031-5da76100-677f-11e8-8705-bb3d358917bb.png)

**Comment by misosec** [comment]
Hello,
yeah, it's me again... :-) So should be the channel "Name"? And which one in my case?

Thanks.

**Comment by firsttris** [comment]
when you go in your ccu to devices you find the channels
![image](https://user-images.githubusercontent.com/1709260/41636742-96e060d8-7450-11e8-94af-2c26bf4d3d45.png)

in my case LEQ0236498:1

**Comment by misosec** [comment]
I see. I changed it's name to  HM-Sec-Win. It should be ok, right?
![image-001 09-06-08](https://user-images.githubusercontent.com/29805226/41642892-f29337a2-7469-11e8-8338-b8fddd3d7959.png)

Thanks

**Comment by firsttris** [comment]
can't tell never done that

**Comment by oliverlorenz** [comment]
I work with the same device and had also some problems to figure out how to open/close and lock/unlock the window. I want to share my results here:

The only parameter to lock/unlock, open/close you need is `LEVEL`

* Open the Window 100%: set LEVEL: 100
* Open the window 50%: set LEVEL: 50
* Unlock the window: set LEVEL: 0
* Lock the Window: set LEVEL: -0.5

**Comment by misosec** [comment]
> 
> 
> I work with the same device and had also some problems to figure out how to open/close and lock/unlock the window. I want to share my results here:
> 
> The only parameter to lock/unlock, open/close you need is `LEVEL`
> 
>     * Open the Window 100%: set LEVEL: 100
> 
>     * Open the window 50%: set LEVEL: 50
> 
>     * Unlock the window: set LEVEL: 0
> 
>     * Lock the Window: set LEVEL: -0.5

Thank you very much!
