### ISSUE TITLE
working example?

### ISSUE THREAD

**Issue by janningnetworks** [firsttris/node-red-contrib-homematic#2]
do you have a working example? how do i configure the http request to my homematic? thank you!

with my flow:

[{"id":"87b8cdba.0dc03","type":"homematic","z":"8b07ed78.d127f","_method":"Device.listAll","_interface":"","_device":"e79e693c.96bdd8","_valueKey":"","_type":"","_url":"","_interfaceId":"","_value":"","_topic":"AnzeigeGeraete","_username":"","_password":"","_name":"AnzeigeGeraete","x":300,"y":526,"wires":[["95bdbb9a.2b3188","e836bf50.0ea71"]]},{"id":"95bdbb9a.2b3188","type":"debug","z":"8b07ed78.d127f","name":"","active":true,"console":"false","complete":"false","x":782,"y":431,"wires":[]},{"id":"b2606b0b.b23418","type":"inject","z":"8b07ed78.d127f","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"x":144,"y":464,"wires":[["87b8cdba.0dc03"]]},{"id":"e836bf50.0ea71","type":"http request","z":"8b07ed78.d127f","name":"","method":"POST","ret":"obj","url":"http://192.168.2.222:2001/{{{payload}}}","tls":"","x":582,"y":542,"wires":[["95bdbb9a.2b3188"]]},{"id":"e79e693c.96bdd8","type":"homematic-config","z":"8b07ed78.d127f","device":"Bidcos1","serial":"BidCoS-RF:1"}]

i get the following response:

<?xml version="1.0"?> <methodResponse><fault> <value><struct><member><name>faultCode</name><value><i4>-1</i4></value></member><member><name>faultString</name><value>: unknown method name</value></member></struct></value> </fault></methodResponse>

**Comment by firsttris** [comment]
hello jannignetworks,

i have rebuild the project to use another API.
its now much easier to use...

i also have provided working examples..

if you still have issues please open a new issue.

regards
Tristan

**Comment by janningnetworks** [comment]
thanks! i´ll check it out.



janning networks

birger-forell-str. 46

49824 neugnadenfeld

phone +49 5944 599105

fax +49 5944 5999922

www.janning.info



2017-01-10 15:43 GMT+01:00 Tristan Teufel <notifications@github.com>:
