### ISSUE TITLE
Homematic Get

### ISSUE THREAD

**Issue by ich777** [firsttris/node-red-contrib-homematic#3]
Hey Tristan,

i really like your project, but i've get some errors with the getValue.
How can i implement that in my NodeRED?
I'm trying to create a NodeRED without any other software tools like io.Broker or something, but i need the getValue that i'm up to date with my homematic devices.

Regards, Christoph

**Comment by ich777** [comment]
Also i´ve got a great idea how to make things easier with nodered and homemeatic.
But i don´t know how to do it because i'm a hobby programmer and don't have the skills...
Can i contact you in another way?

**Comment by firsttris** [comment]
hey christoph,

this is a good way to contact me

check the vanilla way in readme -->
https://github.com/firsttris/node-red-contrib-homematic#the-vanilla-way

for example

to set value 100
var script = "var d = dom.GetObject(\"BidCos-RF.LEQ0990753:1.LEVEL\");if (d){d.State(\"100\");}";

to get the value
var script = "var d = dom.GetObject(\"BidCos-RF.LEQ0990753:1.LEVEL\");if (d){Write(d.State());}

depends which attribute you want to get in this case its "LEVEL"

im using homematic rega api here but thats also possible with xml rpc

Regards
Tristan

**Comment by ich777** [comment]
Hello Tristan,

im thinking of another way to use nodered with the homematic.
Is it even possible to build it more modular?
So that you have a main module thats connect to the ccu and have other nodes that connect with the devices paired on the ccu and build your own interface with node-ui?

Look at the Loxone UI and programming happens in the same way as in node.

Sorry for my poor english i'm from austria...
I hope you understand what i mean...

What do you think of it?

**Comment by ich777** [comment]
I've tested the get methode but it doesn't work it gives me:

`msg.payload : string[79]
"var d = dom.GetObject("BidCos-RF.MEQ0396382:1.LEVEL");if (d){Write(d.State());}"`

in debug info (By the way theres a typo double ; and no "; at the end of the get.

Regards, Christoph

**Comment by firsttris** [comment]
Hey,

du kannst auch gerne auf deutsch schreiben.

ich verstehe es nicht sooo ganz..
also nur mit node-red benutze ich einen "function node" und sende die nachricht mit einem "http-request node" an die ccu.
mein custom node baut dir quasi nur die nachricht zusammen die du mit einem http-request node versenden kannst.

da die verbindung zustandslos ist (http) gibt es kein "connect" sowas gibt es nur bei (tcp).

Grüße

**Comment by firsttris** [comment]
Schau dir das beispiel mal richtig an:
https://github.com/firsttris/node-red-contrib-homematic#the-vanilla-way

du musst einen function node erstellen mit diesem code:

```javascript
var script = "var d = dom.GetObject(\"BidCos-RF.LEQ0990753:1.LEVEL\");if (d){Write(d.State());}}";
var headers = {};
headers["Content-Length"] = script.length;
headers["Content-Type"] = "application/x-www-form-urlencoded";
msg.headers = headers;
msg.method = "POST";
msg.url = "http://20.1.0.50/tclrega.exe";
msg.payload = script;
return msg;
```

oder du nimmst meinen custom node der dir die nachricht baut.
https://github.com/firsttris/node-red-contrib-homematic#how-to-use-this-node

das ganze dann mit http-request node an die ccu schicken

es gibt auch einen flow den du importieren kannst:
https://github.com/firsttris/node-red-contrib-homematic/blob/master/test/vanilla-vs-node-red-contrib-homematic-example-flow.json

**Comment by ich777** [comment]
Hallo,

ich find deinen Ansatz ja richtig gut, nur war ich erstaunt, wie ähnlich nodered UI mit Loxone ist auch von der Logik dahinter.

Ich hab mir gedacht das es ja einfacher wäre wenn man einen Baustein zB CCU2 hat (mit dem man sich auf die CCU2 connect und falls erforderlich das Passwort eingibt.

Dann noch einen je einen Baustein für die Geräte (Lichtschalter, Dimmer, Temperatursensor) und sich dann alles selbst zusammenbaut mit diversen Diagrammen, Schaltern usw...

Wäre dann sowas wie FHEM in die richtung, nur einfacher find ich und auch benutzerfreundlicher, dann könnte man sich ganz einfach alles in NodeRED konfigurieren und die CCU2 müsste eigentlich nur die Befehle an die Geräte senden, bzw den Status abfragen.

Das wär super für Leute wie mich bzw. Leute die sich damit nicht beschäftigen wollen, versteh mich jetzt nicht falsch, mir gefällt NodeRED, aber ich beschäftig mich erst seit Gestern damit, aber es gefällt mir und ich bin auch soweit das ich alle meine einstellungen auf der CCU2 verwerfe und auf NodeRED umsteige (wird aber noch ein bisschen dauern).

Ich find deine Arbeit hier auf jeden Fall toll und bedanke mich dafür, gefällt mir!

Grüße

EDIT: Hab mir jetzt deinen Flow angesehen, das hab ich schon, nur wollte ich den Status von der CCU2 von einem Gerät auslesen nur hänge ich da.

**Comment by firsttris** [comment]
Hey,

also es gibt ja 2 Bausteine einen für die Nachricht (homematic) und einen zum versenden (http-request).
Für die Schnittstellen "hm rega" und "xml rpc" gibt es soweit ich informiert bin keine Möglichkeit ein Passwort zu aktivieren.

Die Nachricht ist ja meist spezifisch für ein Gerät deshalb wird die Device Id halt beim (homematic) node definiert. (und als config global gespeichert)... d.h. beim nächsten (homematic) node kannst du die ID wieder auswählen) 

Ich finde das ein Vorteil das man den normalen http-request node verwenden kann/muss.

Schließlich soll dir Node-Red erklären wie Netzwerk Kommunikation funktioniert.

Es ist keinesfalls möglich Node-Red mit FHEM zu vergleichen das ist was total anderes.

Grüße

**Comment by ich777** [comment]
Ok danke.
