### ISSUE TITLE
CCU-Daten

### ISSUE THREAD

**Issue by rocklobster42195** [firsttris/node-red-contrib-homematic#4]
Hallo Tristan,
wo werden die CCU-Daten (URL etc) eingetragen?  Ich finde keine Möglichkeit der Konfiguration. Wenn ich beispielsweise die Methode "Interface.setValue" wähle, kann ich die URL nicht mehr eingeben.

Dein Beispiel kann ich auch nicht importieren. Ich bekomme die Fehlermeldung:
Imported unrecognised types:
  ccu-address
  homematic-device

Kannst du mir Starthilfe geben?
Danke dir und viele Grüße
Boris

**Comment by firsttris** [comment]
Hallo Boris,

Diese werden als Configurations Objekte gespeichert, node übergreifend.

check mal den Screenshot:
https://drive.google.com/file/d/0B7mzI0TL-AbUbThZUDV6cFZRdzA/view?usp=sharing
Hab den Button markiert.
Das hab ich mir nicht ausgedacht das ist eine standard node-red componente

Grüße 
Tristan

**Comment by firsttris** [comment]
Das man das beispiel nicht imporiteren kann ist ja echt doof.

Kannst du mal die letzten beiden JSON objekte löschen (zeile 108 bis 122) und den Import nochmal versuchen?
Das sind nämlich die 2 config objekte für ccu addresse und geräte
https://github.com/firsttris/node-red-contrib-homematic/blob/master/test/vanilla-vs-node-red-contrib-homematic-example-flow.json#L108-L122

**Comment by rocklobster42195** [comment]
Genau das ist glaube ich mein Problem. Die CCU-Zeile fehlt bei mir komplett:
[https://drive.google.com/file/d/0B8BD5yUGqVE2NHk0TEtaY243SW8/view?usp=sharing](https://drive.google.com/file/d/0B8BD5yUGqVE2NHk0TEtaY243SW8/view?usp=sharing)

Ohne die beiden JSON-Objekte kann ich dein Beispiel importieren. Über den angepassten Vanilla-Node funktioniert es auch.

**Comment by firsttris** [comment]
Irgendwie hast du wohl eine ältere Version installiert... es sollten nur die felder existieren die auf meinem screenshot zu sehen sind. deshalb kannst du auch das example nicht importieren.

check mal in deinem node-red-directory/node_modules/node-red-contrib-homematic/package.json -> Version 2.0.4

du kannst  <node-red-directory>/node_modules/node-red-contrib-homematic/ auch löschen

wenn dein npm irgendwie nicht die neuste version installiert versuch mal:

npm install node-red-contrib-homematic@latest -g

oder du clonest einfach das git repo in dieses verzeichnis:

cd node-red-directory/node_modules/
git clone https://github.com/firsttris/node-red-contrib-homematic.git

Ich habe gerade mal von npm installiert um zu prüfen das da nicht irgendwie die alte version deployed ist, passt aber alles.

**Comment by rocklobster42195** [comment]
Ahaaaa. Ist mir erst jetzt aufgefallen, dass immer die v1.0.6 bekommen habe. Warum auch immer.
Jetzt kann ich auch über deinen Node die Lampen schalten. Super! Danke dir schon mal.

Hast du einen Tipp, wie ich in Systemvariablen schreiben kann? Oder soll ich dafür einen neuen Thread aufmachen?

**Comment by firsttris** [comment]
in einem Function Node kannst du auf Systemvariablen mit 
`process.env.ENV_VARIABLE`
zugreifen. ENV_VARIABLE steht für deinen variablen namen.
bin mir nicht sicher ob man so auch schreiben kann weil eigentlich will man Sie ja meistens nur auslesen.

**Comment by firsttris** [comment]
wahrscheinlich meinst du aber Systemvariablen auf der CCU und ich meinte Umgebungsvariablen auf dem System wo nod-red läuft.

glaube nicht das ich es implementiert habe. wenn du es aber mit vanilla mitteln hinbekommst, kann ich es für dich einbauen.
Habe damit aber keine Erfahrung.

**Comment by rocklobster42195** [comment]
Prima! Ich werde es mal ausprobieren.

**Comment by rocklobster42195** [comment]
Ähem. Das war unspektakulär. Die Systemvariablen sind DOM-Objekte:
`var script = "var d = dom.GetObject(\"Anwesenheit\");if (d){d.State(\"0\");}";
var headers = {};
headers["Content-Length"] = script.length;
headers["Content-Type"] = "application/x-www-form-urlencoded";
msg.headers = headers;
msg.method = "POST";
msg.url = "http://20.1.0.50/tclrega.exe";
msg.payload = script;
return msg;`
