### ISSUE TITLE
Wie übergebe ich denn Values an die Node?

### ISSUE THREAD

**Issue by mastix** [firsttris/node-red-contrib-homematic#5]
Hey,

erstmal coole Sache, dass du hier nen RPC-Wrapper gecoded hast!

Eine Frage: Ich bin gerade dabei von OpenHab zu wechseln und frage mich gerade wie ich denn einen Input-Wert (z.b. einen Temperaturwert von MQTT) weitergeben kann?

Aktuell lasse ich "Value" leer und der HTTP-Request schickt auch keinen Value mit. Trage ich manuell "16" in die node properties ein, kommt auch 16 an und wird gesetzt... gibt es zufällig einen Platzhalter (dachte es wäre so etwas wie "{{msg.payload}}") was ich nutzen kann, um das "Value" Feld korrekt per Input zu befüllen?

Mag sein, dass das eine absolute Newbie-Frage ist, aber wenn ich mir den Code anschaue, sieht es so aus, als ob das nicht implementiert wurde, d.h. ich muss den Wert manuell im Node setzen, korrekt?

**Comment by mastix** [comment]
Hab mal nen Pull Request (https://github.com/firsttris/node-red-contrib-homematic/pull/6) gestellt, der dieses Feature hinzufügt! :)

Sag Bescheid, ob das für dich passt.

**Comment by firsttris** [comment]
gefällt mir sehr gut, herzlichen dank für deine Mühe!

**Comment by mastix** [comment]
Hallo Tristan,

klar. Gerne.

Habe gerade nur gesehen, dass mein Bild der ReadMe irgendwie größer ist als deins, eventuell kannst du das noch anpassen und commiten. 👍 

Viele Grüße,

Sascha

**Comment by firsttris** [comment]
hab leider gerade garkein node-red installiert... vielleicht wenns dir keine mühe macht kannst du noch einen Screen in kleiner Auflösung comitten?

**Comment by mastix** [comment]
Done! :) PR gestellt.

**Comment by firsttris** [comment]
herzlichen dank!

**Comment by firsttris** [comment]
Eine Frage:
mit der ccu2 kann man nicht über mqtt sprechen oder ? nur per http ?

**Comment by mastix** [comment]
Nee, leider nicht. Deshalb hab ich meine eigene Queue am Laufen und node-red schickt (hoffentlich bald) die Nachrichten von der CCU (per Pull alle x Sekunden, da die CCU leider keine Events schickt) auf meine Queue. Mein OpenHAB macht das schon... aber ich will halt weg von Java! 🗡
