### ISSUE TITLE
After Updating on the latest Version I get the Error: Flows stopped due to missing node types. Check logs for details.

### ISSUE THREAD

**Issue by heydemar** [firsttris/node-red-contrib-homematic#9]
Hey, 

i have updated your Node - after the Update my Node-Red show me the following error: 
Flows stopped due to missing node types. Check logs for details. 

The Node-Red Log show: 
27 Nov 12:06:01 - [info] Waiting for missing types to be registered:
27 Nov 12:06:01 - [info]  - homematic-config

And I found this in my Node-Red GUI: 

This node is a type unknown to your installation of Node-RED.

If you deploy with the node in this state, it's configuration will be preserved, but the flow will not start until the missing type is installed.

See the Info side bar for more help

I need help 

Thanks!

//EDIT: Resolved: http://www.imakeyouintelligent.com/node-red-flows-stopped-due-to-missing-node-types-check-logs-for-details/

**Comment by firsttris** [comment]
Hey Marvin,

hört sich dannach an als ob die Config für das Node fehlen würde....

Kannst du mir sagen:

Ist es ein fehler von meinem Node? 
Oder ist irgendwas so das es für den Benutzer nicht sofort klar ist?

Nice Blog!!

Grüße
Tristan

**Comment by heydemar** [comment]
Hi Tristan, 

das Problem habe ich nach Update der node-red-contrib-homematic erhalten. Und genau wie du es beschreibst, es wurde wohl die Node (-homematic-config) entfernt, diese war natürlich noch in meiner Konfiguration, wurde mir dann auch in der Auflistung (Configuration Nodes") als "Unknown" angezeigt. 
Konnte dann über das Menü "Configuration Nodes" jedoch den Node entfernen und alles war wieder gut nach einem Neustart von Node-Red. 

Zusammenfassend, es scheint ein Fehler von deiner Node zu sein. Nach dem genauen lesen der Fehlermeldung war mir klar, was zu tun ist - ich weiß natürlich nicht wie es anderen Usern geht ;) 

Danke für das Lob, falls du die Plattform auch für Projekte, Nodes oä. nutzen möchtest, melde dich gerne. 

Gruß Marvin

**Comment by firsttris** [comment]
Hey,

hatte etwas zeit es nachzuvollziehen.

in der neuen Version speichern wir mehrere Objekte (ccu-adress und devices) in einem Konfigurationsobjekt. Den alten namen "homematic-config" vom ehemlaigen Konfigurationsobjekt gibts einfach nicht mehr.

Der Fehler passiert also nur beim aktualisieren des Nodes.

Node-Red stoppt quasi weil da eine config objekt existiert welches nicht registiert wird.

Grüße
Tristan
